### ISSUE TITLE
Appreciation and Query

### ISSUE THREAD

**Issue by quadroli** [seladb/pickledb-rs#18]
Am really happy to have come across this, am an aspiring Rust developer and it really appeals to me, and so this year i want to write a small database system and so i have been researching on the matter, and have truly taking a liking to this, seems simple and useable, and gentle to use to,

And so, i would love to inquire, what would be the difference between using this crate vs simply writing and reading to a file probably serializing with json, cause what am getting so far is that either files would be loaded to memory at runtime and neither  are accesed from disk, well, one difference i do spot is that for sure handling the data should be much easier using this and also it has a few more in built features to take advantage of, so yeah, seems pretty neat, could you kindly enlighten me more on this matter, would be highly appreciated,

**Comment by seladb** [comment]
thanks for the kind words @quadroli ! 
You're absolutely right, this project isn't a fully-featured database and it doesn't aim to be 😃 
You can certainly look at it as an easier way to read and write data from/to files, but I prefer to look at it as a simple key-value store that can be stored in a file in different formats (currently supported are JSON, YAML, Bincode and CBOR).
My goal was always to keep it simple and lightweight. I had thoughts to expand it so it behaves more like a database but I haven't gotten to it yet. Please let me know what you think

**Comment by quadroli** [comment]
Ahh, understood, well, am eager to use it, seems like exactly what i was looking for, a nice and efficient way to store and retrieve some data with ease and little overhead, also interested in seeing how it grows, hope i can even contribute to it in the near future, would be fun

**Comment by quadroli** [comment]
Wow, just used it today, enjoyed a whole lot, guess only thing i'd desire for it to have would be making the db files read-only by default, would be pretty undesirable having them fumbled about from tine to time. Dope 👌🏽
