### ISSUE TITLE
[issue]can not look up values having used bin serialization

### ISSUE THREAD

**Issue by quadroli** [seladb/pickledb-rs#19]
https://user-images.githubusercontent.com/58091631/105632226-21656b00-5e63-11eb-99e7-c74872ce221d.mp4

[Link to the sample code](https://github.com/quadroli/show)

**Comment by seladb** [comment]
I'm sorry for the late response. I'll take a look and get back to you soon

**Comment by seladb** [comment]
I found the issue!

when you update the db [here](https://github.com/quadroli/show/blob/cc958e83e64e65745353d21f0b40de66726cfab8/src/main.rs#L54) you use `u16` but when you read from it [here](https://github.com/quadroli/show/blob/cc958e83e64e65745353d21f0b40de66726cfab8/src/main.rs#L70) you use `u32`. The Bin format is probably more sensitive to this than CBOR (not sure why).

Please let me know if you have any more questions.

**Comment by quadroli** [comment]
oh shid! 
,now works 👌

> The Bin format is probably more sensitive to this than CBOR (not sure why).
may probably be in the implementation, all other formats are by Serde, except it

> Please let me know if you have any more questions.
Nah, no more at the moment, at least now we know of this, feel it may be safe to close the issue now,
