### ISSUE TITLE
Compatibility with the python version

### ISSUE THREAD

**Issue by hardliner66** [seladb/pickledb-rs#2]
Is this 100% compatible with the python version? And if so, are there plans to keep it compatible?

**Comment by seladb** [comment]
It’s not 100% compatible with the Python version but it’s close to that.
I think I’d like to keep it compatible, but it really depend on requests from users. I may add features in the future that aren’t there in the Python version.
May I ask why are you asking? Do you prefer I keep it compatible or do you have features in mind that you’d like me to add?

**Comment by hardliner66** [comment]
I asked because it has the same name as the python version and I think it should be noted somewhere if it's compatible and if it will stay this way.

If it's compatible it can be used to port applications from python to rust, if they are using PickleDb.

If compatibility is broken, it would probably be better to change the name to something different, so that there will be no confusion between the two.

**Comment by seladb** [comment]
Currently it's almost compatible. Of course Rust and Python are different programming languages so it'll never actually be 100% compatibility. I agree with you that if I decide to change the interface it'd be a good idea to change the name too

**Comment by seladb** [comment]
Please let me know if we can close this issue

**Comment by seladb** [comment]
I'm closing this issue for now. Please reopen it if needed
